Croissant_Rouge/Controllers/ShippersController.cs
using Croissant_Rouge.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using Croissant_Rouge.Utility;

namespace Croissant_Rouge.Controllers;

public class ShippersController : Controller

{
    private readonly MyContext _context;
    public ShippersController(MyContext context)
    {
        _context = context;
    }



    [HttpGet("/shipper/dashboard")]
    public IActionResult ShipperDashboard()
    {
        if (HttpContext.Session.GetInt32("userId") == null)
        {
            return RedirectToAction("LoginUser","Users");
        }

        int? userId = (int)HttpContext.Session.GetInt32("userId");
        string? firstname = HttpContext.Session.GetString("FirstName");



       List <Donation> AllDonations =
            _context.Donations
            .Include(s => s.Donner)
            .Include(h => h.Shipment)
            .Where(s => s.status == StaticData.Status.Valid)
            .ToList();

        List<Shipment> AllShippments =
            _context.Shipments
            .Include(g=> g.Donation)
            .ThenInclude(h => h.Donner)
            .Where(s => s.UserId == userId && s.ShipStatus == StaticData.ShipStatus.Received)
            .ToList();


        ShipmentAndDonations vm = new ShipmentAndDonations();
        vm.Alldonations = AllDonations;
        vm.AllShippments = AllShippments;


        return View(vm);
    }


    [HttpPost("/shipdonation")]
    public IActionResult ShipDonation(Shipment newShippment)
    {
        if (ModelState.IsValid)
        {
            var userIdFromSession = HttpContext.Session.GetInt32("userId");
            //newShippment.UserId = (int)HttpContext.Session.GetInt32("userId");
            //1 Add 
            _context.Add(newShippment);

            //2 Save
            _context.SaveChanges();
            return RedirectToAction("ShipperDashboard");
        }
        return RedirectToAction("ShipperDashboard");

    }



    [HttpPost("/shipManydonation")]
    public IActionResult ShipManyDonations(List<Donation> donations)
    {
        Console.WriteLine($"{donations.Count()} *********************");
        //if (ModelState.IsValid)
        //{
        //    int? userId = (int)HttpContext.Session.GetInt32("userId");


        //    //1 Add 
        //    _context.Add(newShipper);

        //    //2 Save
        //    _context.SaveChanges();
        //    return RedirectToAction("ShipperDashboard");
        //}
        return RedirectToAction("ShipperDashboard");

    }









    [HttpPost("donations/{id}/validate")]
    public IActionResult AcceptShipping(int id)
    {
        Shipment? OneShipment = _context.Shipments
            .FirstOrDefault(shipment => shipment.ShipmentId == id);
        OneShipment.ShipStatus = StaticData.ShipStatus.Received;
        _context.SaveChanges();
        return RedirectToAction("ShipperDashboard");
    }



    // ************************* Create Shipper *******************

    [HttpPost("shipper/create")]
    public IActionResult CreateShipper(User newShipper)
    {
        if (ModelState.IsValid)
        {
            // Email Exist ?
            if (_context.Users.Any(u => u.Email == newShipper.Email))
            {
                // True
                ModelState.AddModelError("Email", "Email already in use .");
                return View("CreateShipper");
            }
            else
            {
                // False
                // 1 - Hash Password
                PasswordHasher<User> Hasher = new PasswordHasher<User>();
                newShipper.Password = Hasher.HashPassword(newShipper, newShipper.Password);
                // 2 - Add 
                _context.Add(newShipper);
                // 3 - Save
                _context.SaveChanges();
                // HttpContext.Session.
                return RedirectToAction("ShipperList");
            }
        }
        return View("CreateShipper");
    }

    [HttpGet("shipper/create")]
    public IActionResult CreateShipper()
    {
        if (HttpContext.Session.GetInt32("userId") == null)
        {
            return RedirectToAction("Index");
        }
        return View("CreateShipper");
    }



    // ******************** All Shippers *************************

    [HttpGet("Allshippers")]
    public IActionResult ShipperList()
    {


        if (HttpContext.Session.GetInt32("userId") == null)
        {
            return RedirectToAction("LoginUser", "Users");
        }
        List<User> ShipperList = _context.Users
            .Where(user=> user.Role == StaticData.Roles.Shipper)
            .ToList();
        return View("ShipperList", ShipperList);
    }


    //** ShippAll **


    [HttpGet("ShippAll")]
    public IActionResult ShippAll(int donnerId)
    {
        if (HttpContext.Session.GetInt32("userId") == null)
        {
            return RedirectToAction("LoginUser", "Users");
        }
        List<Donation> userDonnations = _context.Donations
            .Where(donation => donation.UserId == donnerId && donation.status == StaticData.Status.Valid && donation.Shipment.ShipStatus != StaticData.ShipStatus.Received)
            .Include(donation => donation.Donner)
            .Include(donation => donation.Shipment)
            .ToList();

        User? Donator = _context.Users.FirstOrDefault(user => user.UserId == donnerId);

        DonationandUser vl = new DonationandUser();
        vl.Alldonations = userDonnations;
        vl.User = Donator;


        return View(vl);
    }


    //** Delete Shipper **

    [HttpPost("shipper/destroy")]
    public IActionResult DeleteShipper(int userId)
    {
        User? ShipperToDelete = _context.Users.FirstOrDefault(s => s.UserId == userId);
        _context.Users.Remove(ShipperToDelete);
        _context.SaveChanges();
        return RedirectToAction("ShipperList");
    }


}

Croissant_Rouge/Views/Shared/_AdminNavBar.cshtml
<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/ShipperNav.css" asp-append-version="true" />
</head>

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <img src="~/uploads/logo.png"
                 alt=""
                 style="width: 45px; height: 45px"
                 class="rounded-circle" />
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Categories">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Donations" asp-action="AllDonations">All Donations</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Shippers" asp-action="CreateShipper">Create Shipper</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Shippers" asp-action="ShipperList">Our Shippers</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="CreateEvent">Create Event</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Events" asp-action="AllEvents">Our Events</a>
                    </li>
                </ul>
            </div>
            <div>
                <form asp-action="Logout" asp-controller="Users" method="post">
                    <input type="submit" value="Logout" class="btn btn-Link btn-lg">
                </form>
            </div>
        </div>
    </nav>
</header>

Croissant_Rouge/Views/Shared/_Footer.cshtml
<link href="https://cdn.jsdelivr.net/npm/bootstrap-icons/font/bootstrap-icons.css" rel="stylesheet">

<style>
    .site-footer {
        background-color: #e8e8e8;
        padding: 45px 0 20px;
        font-size: 15px;
        line-height: 24px;
        color: #737373;
    }

        .site-footer hr {
            border-top-color: #bbb;
            opacity: 0.5
        }

            .site-footer hr.small {
                margin: 20px 0
            }

        .site-footer h6 {
            color: #3D0C11;
            font-size: 16px;
            text-transform: uppercase;
            margin-top: 5px;
            letter-spacing: 2px
        }

        .site-footer a {
            color: #737373;
        }

            .site-footer a:hover {
                color: #3366cc;
                text-decoration: none;
            }

    .footer-links {
        padding-left: 0;
        list-style: none
    }

        .footer-links li {
            display: block
        }

        .footer-links a {
            color: #737373
        }

            .footer-links a:active, .footer-links a:focus, .footer-links a:hover {
                color: #3366cc;
                text-decoration: none;
            }

        .footer-links.inline li {
            display: inline-block
        }

    .site-footer .social-icons {
        text-align: right
    }

    .copyright-text {
        margin: 0
    }
</style>

<footer class="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <h6>About</h6>
                <p class="text-justify">
                    RedCrescent.tn <i>HERE FOR HUMANITY </i> ©2023 Tunisian Red Crescent.
                    The Tunisian Red Crescent Society, incorporated 7 october 1956, and became a member of the International Red Cross and Red Crescent movement on September 13, 1957.
                </p>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Find Us</h6>
                <ul class="footer-links">
                    <li><a href="https://maps.app.goo.gl/SfxMFY2w4xh8tgAB8">Av Habib bourguiba</a></li>
                    <li><a href="https://maps.app.goo.gl/3EDooU4MhF9zPkNMA">Ariana</a></li>
                    <li><a href="https://maps.app.goo.gl/83DNGrHnFiaCbzPc8">Megrine</a></li>
                    <li><a href="https://maps.app.goo.gl/pQyHmSA4mpJjFHtc9">Kram</a></li>
                    <li><a href="https://maps.app.goo.gl/c2ywG1vNmA3HnRyw9">Bizerte</a></li>
                    <li><a href="https://maps.app.goo.gl/GAZkCTkCLCd3vcsF6">Menzel Bou Zelfa</a></li>
                </ul>
            </div>

            <div class="col-xs-6 col-md-3">
                <h6>Contact Us</h6>
                <ul class="footer-links">
                    <i class="bi bi-telephone">
                        +216 71 325 572 /
                        +216 71 320 630
                    </i>
                    <br />
                    <i class="bi bi-envelope"> contact@croissant-rouge.tn</i>


                </ul>
            </div>
        </div>
        <hr>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-sm-6 col-xs-12">
                <p class="copyright-text">
                    Copyright &copy; 2023 All Rights Reserved by
                    <a href="#">croissant rouge tunisien</a>.
                </p>
            </div>


        </div>
    </div>
</footer>

Croissant_Rouge/Views/Shared/_Layout.cshtml
@{
    int? userId = Context.Session.GetInt32("userId"); // Use nullable int
}


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Croissant_Rouge</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />


    <link rel="stylesheet" href="~/Croissant_Rouge.styles.css" asp-append-version="true" />
    <style>
        .navbar {
            background-size: cover;
            background-attachment: fixed;
            background-color: transparent;
        }
    </style>
</head>



<body>
    <div class="">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @await Html.PartialAsync("_Footer")
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/Home.js" asp-append-version="true"></script>




    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Croissant_Rouge/Views/Shared/_ShipperNav.cshtml
@{
    int? userId = Context.Session.GetInt32("userId");
    var test = ViewData["test"] as string;
}

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/ShipperNav.css" asp-append-version="true" />
</head>

<nav class="navbar navbar-expand-lg navbar-light bg-light p-3  " >
    <div class="container-fluid gap-3 ">
        <img src="~/uploads/logo.png"
             alt=""
             style="width: 45px; height: 45px"
             class="rounded-circle" />
        <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <div class="navbar-nav">
             

                <a asp-controller="Shippers" asp-action="ShipperDashboard" class="nav-item nav-link active">All the Shipments</a>
            </div>



                <div class="navbar-nav ms-auto">
                    <form asp-action="Logout" asp-controller="Users" method="post">
                        <input type="submit" value="Logout" class="btn  btn-lg">
                    </form>
                </div>



        </div>
    </div>
</nav>

Croissant_Rouge/Views/Shared/_UserNav.cshtml
@{
    int? userId = Context.Session.GetInt32("userId");
}



<style>

    .custom-btn {
        width: 250px;
        height: 50px;
        color: #fff;
        border-radius: 5px;
        padding: 10px 25px;
        font-family: Roboto,Arial,Helvetica Neue,Helvetica,sans-serif;
        font-weight: 900;
        background: transparent;
        cursor: pointer;
        transition: all 0.3s ease;
        position: relative;
        display: inline-block;
        outline: none;
        text-align: center;
    }






    /* 13 */
    .btn-13 {
        background-color: #e3001b;
        background-image: linear-gradient(315deg, #e3001b 0%, #aa0f19 74%);
        border: none;
        z-index: 1;
    }





    .navbar-nav {
        list-style: none;
        padding: 0;
        display: flex;
        font-family: Sans-serif Arial Verdana Helvetica;
    }

    .nav-item {
        margin-right: 15px;
    }

    .dropdown {
        position: relative;
        display: inline-block;
    }

        .dropdown:hover .dropdown-menu {
            display: block;
        }

    .dropdown-menu {
        display: none;
        position: absolute;
        top: 100%;
        left: 0;
        background-color: #fff;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        border-radius: 4px;
        padding: 10px;
    }

    .dropdown-item {
        display: block;
        padding: 5px;
        color: #333;
        text-decoration: none;
    }

        .dropdown-item:hover {
            background-color: #f0f0f0;
        }
</style>

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/ShipperNav.css" asp-append-version="true" />
</head>

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow  position-top  top:0 width:100% mb-3">
        <div class="container-fluid">
            <img src="~/uploads/logo.png"
                 alt=""
                 style="width: 70px; height: 70px"
                 class="rounded-circle" />
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
                <ul class="navbar-nav flex-grow-1 " style="margin-left:30px">
                    <li class="nav-item ">
                        <a class="nav-link text-dark" style=" font-size: 1.2rem" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" style=" font-size: 1.2rem" asp-area="" asp-controller="Users" asp-action="Categories">Categories</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" style=" font-size: 1.2rem" asp-area="" asp-controller="Events" asp-action="AllEvents">Events</a>
                    </li>

                </ul>
                @if (userId.HasValue)
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link  custom-btn btn-13" style="color:white ;font-size: 1.2rem" asp-area="" asp-controller="Donations" asp-action="Donate">Contribute Now</a>
                        </li>

                        <li class="nav-item dropdown">
                            <a class="nav-link text-dark dropdown-toggle" style=" font-size: 1.2rem" asp-area="" asp-controller="Users" asp-action="MyProfile">

                                My Profile
                            </a>
                            <div class="dropdown-menu" aria-labelledby="profileDropdown">
                                <a class="nav-link text-dark" style=" font-size: 1.2rem" asp-area="" asp-controller="Users" asp-action="EditProfile">Edit Profil</a>
                            </div>


                        </li>
                        <li class="nav-item">
                            <form asp-action="Logout" asp-controller="Users" style=" font-size: 1.2rem" method="post">
            
                                <input type="submit" value="Logout" class="nav-link text-dark" style="background-color:white; border:hidden ;font-weight:400">
                            </form>
                        </li>
                    </ul>


                }
                else
                {
                    <ul class="navbar-nav">

                        <li class="nav-item">
                            <a class="nav-link text-dark" style=" font-size: 1.2rem" asp-area="" asp-controller="Users" asp-action="Login">Login</a>
                        </li>
                    </ul>

                }

            </div>
        </div>
    </nav>
</header>

Croissant_Rouge/Views/Shared/_VisitorNav.cshtml
@{
    int? userId = Context.Session.GetInt32("userId");
}

<head>
    <meta charset="utf-8" />
    <link rel="stylesheet" href="~/css/ShipperNav.css" asp-append-version="true" />
</head>

<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow  position-top  top:0 width:100% mb-3">
        <div class="container-fluid">
            <img src="~/uploads/logo.png"
                 alt=""
                 style="width: 45px; height: 45px"
                 class="rounded-circle" />
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Categories">Categories</a>
                    </li>
                </ul>
                @if (userId.HasValue)
                {
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a class="nav-link text-dark ml-auto" asp-area="" asp-controller="Users" asp-action="MyProfile">My Profile</a>
                        </li>
                        <li class="nav-item">
                            <form asp-action="Logout" asp-controller="Users" method="post">
                                <input type="submit" value="Logout" class="btn btn-link btn-lg">
                            </form>
                        </li>
                    </ul>


                }
                else
                {
                    <ul class="navbar-nav">

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="LoginUser">Login</a>
                        </li>
                    </ul>

                }

            </div>
        </div>
    </nav>
</header>